info: experiment information

gpu: True
run_with_slurm: False
data_folder: /path/to/data
vis: False
observe: False
fullset: False

dataset: cifar10
valid_ratio: 0.222222 # 2/9
model: resnet18
pretrained: True
criterion: cross_entropy
optimizer: sgd
lr_sched: multistep_lr

rnd_seed: 123
num_epochs: 32
batch_size: 128
lrate: 0.01
patience: 5
weight_decay: 0.0001
momentum: 0.9
grad_clip: False

multi_label: False

selection_method: data_si&n-dim&cluster
# Data SI: data_si&n-dim&cluster
# Data SI approx: data_si_approx&1-dim&cluster
# GradNorm: gradnorm&1-dim&thresh
# GradNorm approx: gradnorm_approx&1-dim&thresh
# Random: random&1-dim&topratio
# Margin: smallest_margin&1-dim&topratio
# Confidence: least_confidence&1-dim&topratio

data_val_batch_size: 128

sample_size: 0.3
lr_adjust: True

use_coreset: False
